id = "d"
name = "D"
description = "D language support"
version = "0.0.8"
schema_version = 1
authors = ["Garrett D'Amore <garrett@staysail.tech>"]
repository = "https://github.com/staysail/zed-d"

[language_servers.serve-d]
name = "serve-d"
language = "D"

[grammars.d]
repository = "https://github.com/gdamore/tree-sitter-d"
commit = "5dd64071dac90497ac5ad12e583bb03e46f8eb86"
