id = "d"
name = "D"
description = "D language support"
version = "0.0.6"
schema_version = 1
authors = ["Garrett D'Amore <garrett@staysail.tech>"]
repository = "https://github.com/staysail/zed-d"

[language_servers.serve-d]
name = "serve-d"
language = "D"

[grammars.d]
repository = "https://github.com/gdamore/tree-sitter-d"
commit = "c067ff38b84d860c993d8b8906124e96694593e4"
