id = "d"
name = "D"
description = "D language support"
version = "0.0.5"
schema_version = 1
authors = ["Garrett D'Amore <garrett@staysail.tech>"]
repository = "https://github.com/staysail/zed-d"

[language_servers.serve-d]
name = "serve-d"
language = "D"

[grammars.d]
repository = "https://github.com/gdamore/tree-sitter-d"
commit = "143a2e66c1a55973ed0d4704b4fd118c854b430d"
